# Generated by Django 3.0.5 on 2020-05-10 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_contact',
            field=models.IntegerField(),
        ),
    ]
